/////////////////////////////
// Projekt GFK04
// Michal Domin
// Damian Raczynski
// Kacper Osuch
/////////////////////////////
#ifndef __guiMyFrame1__
#define __guiMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "gui.h"

//// end generated include
#include <wx/wx.h>
#include <fstream>
#include <algorithm>
#include <vector>
#include <array>
#include <functional>
#include <cmath>
#include <wx/dcbuffer.h>
/** Implementing MyFrame1 */
class guiMyFrame1 : public MyFrame1
{
protected:
    // Handlers for MyFrame1 events.
    void loadButtonClick(wxCommandEvent& event);
    void saveButtonClick(wxCommandEvent& event);
    void OnChoice(wxCommandEvent& event);
    void previousSliceClick(wxCommandEvent& event);
    void nextSliceClick(wxCommandEvent& event);
public:
    /** Constructor */
    guiMyFrame1(wxWindow* parent);
    //// end generated class members
    wxBitmap MemoryBitmap;
    wxImage image;
    void DrawMap();
    void Repaint();
    double minVal;
    double maxVal;
    double getVal(std::array<double, 3>& x0);
    std::vector<std::array<double, 3>> plaszczyzna() const;
    double odl(std::array<double, 4>& a, std::array<double, 4>& b);
    bool compare(std::array<double, 4> a, std::array<double, 4> b);
    std::vector<std::array<double, 4>> data;
    std::vector<std::vector<std::vector<std::array<double, 2>>>> datas;
    int ix = 0, iy = 1, iz = 1;
    double minDim;
    double maxDim;
    double modifier;
    int currentSlice;
};

#endif // __guiMyFrame1__
